feat: v1 release (#129)

diff --git a/.trunk/trunk.yaml b/.trunk/trunk.yaml
--- a/.trunk/trunk.yaml
+++ b/.trunk/trunk.yaml
@@ -2,38 +2,67 @@
 # To learn more about the format of this file, see https://docs.trunk.io/reference/trunk-yaml
 version: 0.1
 cli:
-  version: 1.22.9
+  version: 1.25.0
 # Trunk provides extensibility via plugins. (https://docs.trunk.io/plugins)
 plugins:
   sources:
     - id: trunk
-      ref: v1.6.7
+      ref: v1.10.2
       uri: https://github.com/trunk-io/plugins
 # Many linters and tools depend on runtimes - configure them here. (https://docs.trunk.io/runtimes)
 runtimes:
   enabled:
-    - go@>=1.23.6 # stdlib vulnerability in 1.23.5
-    - node@>=22.0.0
-    - python@3.10.8
+    - go@1.25.11
+    - node@>=24.0.0
+    - python@3.14.4
   definitions:
-    - type: go
-      system_version: allowed
     - type: node
-      system_version: allowed
+      system_version: ignored
 # This is the section where you manage your linters. (https://docs.trunk.io/check/configuration)
 lint:
+  ignore:
+    - linters: [markdownlint]
+      paths:
+        - .github/docs/**
+
   enabled:
-    - checkov@3.2.360
+    - golangci-lint2@2.12.2
+    - bandit@1.9.4
+    - black@26.5.1
+    - grype@0.114.0
+    - isort@8.0.1
+    - pinact@4.1.0
+    - ruff@0.15.18
+    - taplo@0.10.0
+    - actionlint@1.7.12
+    - hadolint@2.14.0
+    - markdownlint@0.49.0
+    - shellcheck@0.11.0
+    - shfmt@3.6.0
+    - checkov@3.3.1
     - git-diff-check
     - gofmt@1.20.4
-    - golangci-lint@1.63.4
-    - osv-scanner@1.9.2
-    - prettier@3.4.2
-    - trufflehog@3.88.4
-    - yamllint@1.35.1
+    - osv-scanner@2.4.0
+    - prettier@3.8.4
+    - trufflehog@3.95.6
+    - yamllint@1.38.0
 actions:
   enabled:
     - trunk-announce
     - trunk-check-pre-push
     - trunk-fmt-pre-commit
     - trunk-upgrade-available
+    - prevent-dist-binary-commit
+  definitions:
+    - id: prevent-dist-binary-commit
+      triggers:
+        - git_hooks: [pre-commit]
+      run: |
+        if git diff --cached --name-only --diff-filter=ACMR | grep -Eq '^dist/wow-build-tools(\.exe)?$'; then
+          echo "error: refusing to commit generated binary in dist/"
+          echo "error: unstage it with: git restore --staged dist/wow-build-tools dist/wow-build-tools.exe"
+          exit 1
+        fi
+tools:
+  runtimes:
+    - node
