refactor: move guts of upload_curse command to the upload package (#37)

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -42,12 +42,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Trunk Cache
-        uses: actions/cache@v5
-        with:
-          key: trunk-cache-${{ hashFiles('**/trunk.yaml') }}
-          path: ~/.cache/trunk
-
       - name: Trunk Code Quality
         uses: trunk-io/trunk-action@v1
 
@@ -69,46 +63,47 @@ jobs:
       - name: Go cache paths
         id: go-cache-paths
         run: |
-          [ -d $(go env GOCACHE) ] && chmod -R 0755 $(go env GOCACHE)
-          [ -d $(go env GOMODCACHE) ] && chmod -R 0755 $(go env GOMODCACHE)
-          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
-          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
-
-      # Cache go build cache, used to speedup go test
-      - name: Go Build Cache
-        uses: actions/cache@v5
-        with:
-          path: ${{ steps.go-cache-paths.outputs.go-build }}
-          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
-
-      # Cache go mod cache, used to speedup builds
-      - name: Go Mod Cache
-        uses: actions/cache@v5
-        with:
-          path: ${{ steps.go-cache-paths.outputs.go-mod }}
-          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
+          GOPATHBIN=$(go env GOPATH)/bin
+          [ -d $GOPATHBIN ] && chmod -R 0755 $GOPATHBIN
+          echo "go-tool=$GOPATHBIN" >> $GITHUB_OUTPUT
 
       - name: Install Go dependencies
         run: go mod download
 
+      - name: Go Tool Cache
+        uses: actions/cache@v5
+        with:
+          path: ${{ steps.go-cache-paths.outputs.go-tool }}
+          key: ${{ runner.os }}-go-tools-${{ hashFiles('**/go.tools') }}
+
       - name: Install tools
         run: |
-          go install github.com/medyagh/gopogh/cmd/gopogh@1885ea840fbc9b32f018d792342adb919b7b9009
-          go install github.com/cancue/covreport@3fe392bcb4a978ff1f94dbf1367d992c4b3a67d6
+          for tool in $(cat go.tools); do
+            go install "$tool"
+          done
 
       - name: Run tests
         run: |
-          make test-ci
+          mkdir -p ./.coverage
+          echo "Running tests with coverage"
+          go test -v ./... -coverpkg=./... -coverprofile="./.coverage/cover.out" -json > .coverage/test-report.json || true
+          echo "Generating reports"
+          gopogh -in .coverage/test-report.json -out_summary .coverage/test-summary.json -out_html .coverage/test-report.html 1> /dev/null
+          go tool cover -html=./.coverage/cover.out -o .coverage/cover.html
+          covreport -i .coverage/cover.out -o .coverage/report.html
           NumberPassed=$(cat ./.coverage/test-summary.json | jq '.NumberOfPass')
           NumFailed=$(cat ./.coverage/test-summary.json | jq '.NumberOfFail')
           TotalTests=$(cat ./.coverage/test-summary.json | jq '.NumberOfTests')
           TotalTime=$(cat ./.coverage/test-summary.json | jq '.TotalDuration')
+
+          echo ""
           echo "Tests passed: $NumberPassed / $TotalTests in $TotalTime seconds."
           if [ "$NumFailed" -ne "0" ]; then
+            echo "Tests failed: $NumFailed"
             exit 1
           fi
 
-      - name: Upload coverage
+      - name: Upload test and coverage reports
         uses: actions/upload-artifact@v4
         with:
           name: coverage
