test out dist check

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -5,32 +5,31 @@ on:
 permissions: {}
 
 jobs:
-  docker-build:
+  check-dist:
     runs-on: ubuntu-latest
     permissions:
       contents: read
-      actions: write
-      id-token: write
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Build Docker image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: false
-          tags: wow-build-tools:pr-${{ github.event.pull_request.number }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          load: true
-
-      - name: Smoke test Docker image
+      - name: Build binary
         run: |
-          docker run --volume $(pwd):/github/workspace --rm wow-build-tools:pr-${{ github.event.pull_request.number }} /build --help
+          go build -o dist/wow-build-tools
+
+      - name: Verify 'dist' is up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "Error: 'dist' directory is not up to date. Please run 'go build -o dist/wow-build-tools' and commit the changes."
+            git status --porcelain
+            exit 1
+          else
+            echo "'dist' directory is up to date."
+          fi
+
+      - name: Smoke test built binary
+        run: |
+          dist/wow-build-tools build --help
 
   trunk-check:
     runs-on: ubuntu-latest
@@ -114,7 +113,7 @@ jobs:
     name: Passing PR Checks
     runs-on: ubuntu-latest
     if: always()
-    needs: [trunk-check, test, docker-build]
+    needs: [check-dist, trunk-check, test]
     steps:
       - name: Export needs results as JSON
         id: export-needs
diff --git a/.github/workflows/push-main.yml b/.github/workflows/push-main.yml
--- a/.github/workflows/push-main.yml
+++ b/.github/workflows/push-main.yml
@@ -39,26 +39,8 @@ jobs:
         id: go-cache-paths
         run: |
           GOPATHBIN=$(go env GOPATH)/bin
-          [ -d $(go env GOCACHE) ] && chmod -R 0755 $(go env GOCACHE)
-          [ -d $(go env GOMODCACHE) ] && chmod -R 0755 $(go env GOMODCACHE)
           [ -d $GOPATHBIN ] && chmod -R 0755 $GOPATHBIN
-          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
-          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
           echo "go-tool=$GOPATHBIN" >> $GITHUB_OUTPUT
-
-      # Cache go build cache, used to speedup go test
-      - name: Go Build Cache
-        uses: actions/cache@v5
-        with:
-          path: ${{ steps.go-cache-paths.outputs.go-build }}
-          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
-
-      # Cache go mod cache, used to speedup builds
-      - name: Go Mod Cache
-        uses: actions/cache@v5
-        with:
-          path: ${{ steps.go-cache-paths.outputs.go-mod }}
-          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
 
       - name: Install Go dependencies
         run: go mod download
@@ -92,35 +74,34 @@ jobs:
           path: ./.coverage
           include-hidden-files: true
 
-  docker-build:
+  check-dist:
     runs-on: ubuntu-latest
     permissions:
       contents: read
-      actions: write
-      id-token: write
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Build Docker image
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          push: false
-          tags: wow-build-tools:pr-${{ github.event.pull_request.number }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          load: true
-
-      - name: Smoke test Docker image
+      - name: Build binary
         run: |
-          docker run --volume $(pwd):/github/workspace --rm wow-build-tools:pr-${{ github.event.pull_request.number }} /build --help
+          go build -o dist/wow-build-tools
+
+      - name: Verify 'dist' is up to date
+        run: |
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "Error: 'dist' directory is not up to date. Please run 'go build -o dist/wow-build-tools' and commit the changes."
+            git status --porcelain
+            exit 1
+          else
+            echo "'dist' directory is up to date."
+          fi
+
+      - name: Smoke test built binary
+        run: |
+          dist/wow-build-tools build --help
 
   release:
-    needs: [trunk-check, test, docker-build]
+    needs: [trunk-check, test, check-dist]
     runs-on: ubuntu-latest
     permissions:
       contents: write
